
CREATE TABLE `BANDEIRAS` (
`ID_BANDEIRA` int NOT NULL AUTO_INCREMENT,
`NOME` varchar(100) NULL,
PRIMARY KEY (`ID_BANDEIRA`) 
);

CREATE TABLE `PRODUTOS` (
`ID_PRODUTO` bigint NOT NULL AUTO_INCREMENT,
`NOME_PRODUTO` varchar(100) NOT NULL,
`ID_BANDEIRA` int NOT NULL,
PRIMARY KEY (`ID_PRODUTO`) ,
CONSTRAINT `fk_PRODUTOS` FOREIGN KEY (`ID_BANDEIRA`) REFERENCES `BANDEIRAS` (`ID_BANDEIRA`)
);

CREATE TABLE `CLIENTE` (
`ID_PESSOA` bigint NOT NULL AUTO_INCREMENT,
`NOME` VARCHAR(100) NOT NULL,
`CPF` VARCHAR(20) NOT NULL,
`EMAIL` VARCHAR(100) NOT NULL,
`DATANASCIMENTO` DATETIME NOT NULL,
PRIMARY KEY (`ID_PESSOA`) 
);

CREATE TABLE `CONTAS` (
`ID_CONTA` bigint(255) NOT NULL AUTO_INCREMENT,
`ID_PESSOA` bigint NOT NULL,
`ID_PRODUTO` bigint NOT NULL,
`LIMITE_TOTAL` decimal NOT NULL,
`LIMITE_DISPONIVEL` decimal NOT NULL,
PRIMARY KEY (`ID_CONTA`) ,
CONSTRAINT `fk_CONTAS` FOREIGN KEY (`ID_PESSOA`) REFERENCES `CLIENTE` (`ID_PESSOA`),
CONSTRAINT `fk_CONTAS_1` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTOS` (`ID_PRODUTO`)
);


CREATE TABLE `STATUS_CARTAO` (
`ID_STATUS` INT NOT NULL AUTO_INCREMENT,
`DESCRICAO_STATUS` varchar(50) NULL,
PRIMARY KEY (`ID_STATUS`) 
);

CREATE TABLE `CARTOES` (
`ID_CARTAO` bigint(255) NOT NULL AUTO_INCREMENT,
`ID_CONTA` bigint(255) NOT NULL,
`CARTAO_MASCARADO` varchar(20) NOT NULL,
`DATA_VALIDADE` DATETIME NOT NULL,
`CVV_CRIPTO` varchar(5) NOT NULL,
`STATUS` INT NOT NULL,
`DATA_STATUS` DATETIME NULL,
PRIMARY KEY (`ID_CARTAO`) ,
CONSTRAINT `fk_CARTOES` FOREIGN KEY (`ID_CONTA`) REFERENCES `CONTAS` (`ID_CONTA`),
CONSTRAINT `fk_CARTOES_status` FOREIGN KEY (`STATUS`) REFERENCES `STATUS_CARTAO` (`ID_STATUS`)
);

CREATE TABLE `TRANSACOES` (
`ID_TRANSACAO` bigint NOT NULL AUTO_INCREMENT,
`ID_CONTA` bigint NOT NULL,
`VALOR` decimal NOT NULL,
`DATA_TRANSACAO` datetime NOT NULL,
`NOME_ESTABELECIMENTO` varchar(100) NOT NULL,
PRIMARY KEY (`ID_TRANSACAO`) ,
CONSTRAINT `fk_TRANSACOES` FOREIGN KEY (`ID_CONTA`) REFERENCES `CONTAS` (`ID_CONTA`)
);